import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  // Hash passwords
  const adminHash = await bcrypt.hash('admin123', 12);
  const clientHash = await bcrypt.hash('client123', 12);

  // Create admin user
  await prisma.user.upsert({
    where: { email: 'admin@rainbow-colors.tn' },
    update: {},
    create: {
      email: 'admin@rainbow-colors.tn',
      password: adminHash,
      firstName: 'Admin',
      lastName: 'Rainbow',
      role: 'ADMIN',
    },
  });

  // Create demo customer
  await prisma.user.upsert({
    where: { email: 'client@demo.tn' },
    update: {},
    create: {
      email: 'client@demo.tn',
      password: clientHash,
      firstName: 'Client',
      lastName: 'Demo',
      phone: '+216 29 253 908',
      address: 'Route de Gabès Km 4,5',
      city: 'Sfax',
      role: 'CUSTOMER',
    },
  });

  // Seed categories
  const categoriesData = [
    { name: 'Peintures Sols', slug: 'peintures-sols', description: 'Peintures pour sols et parkings', icon: '🏭', color: '#7c3aed' },
    { name: 'Peintures Bois', slug: 'peintures-bois', description: 'Laqués et peintures pour bois', icon: '🚪', color: '#f97316' },
    { name: 'Enduits', slug: 'enduits', description: 'Enduits et mortiers', icon: '🧱', color: '#16a34a' },
    { name: 'Enduits Traditionnels', slug: 'enduits-traditionnels', description: 'Enduits traditionnels à la chaux', icon: '🏛️', color: '#d97706' },
    { name: 'Vernis', slug: 'vernis', description: 'Vernis et protections', icon: '✨', color: '#0d9488' },
    { name: 'Traitements Métal', slug: 'traitements-metal', description: 'Anti-rouille et traitements', icon: '🔩', color: '#dc2626' },
    { name: 'Étanchéité', slug: 'etancheite', description: "Produits d'étanchéité", icon: '☔', color: '#06b6d4' },
    { name: 'Enduits de Finition', slug: 'enduits-finition', description: 'Enduits de lissage et garnissage', icon: '🪒', color: '#8b5cf6' },
    { name: 'Colles', slug: 'colles', description: 'Ciments colle et colles à carrelage', icon: '🔧', color: '#eab308' },
    { name: 'Enduits de Façade', slug: 'enduits-facade', description: 'Enduits de façade tyrolienne', icon: '🏠', color: '#f59e0b' },
    { name: 'Peintures Murales', slug: 'peintures-murales', description: 'Peintures acryliques intérieur/extérieur', icon: '🎨', color: '#2563eb' },
  ];

  for (const cat of categoriesData) {
    await prisma.category.upsert({
      where: { slug: cat.slug },
      update: {},
      create: cat,
    });
  }

  // Fetch categories to get IDs
  const cats = await prisma.category.findMany();
  const getCatId = (name: string) => cats.find((c) => c.name === name)?.id ?? 1;

  // Seed products
  const productsData = [
    {
      name: 'Peinture à l’eau Vrailatex 40',
      slug: 'peinture-a-l-eau-vrailatex-40',
      description: 'Peinture à l’eau Vrailatex 40 - Produit Rainbow Colors au prix HT indiqué.',
      price: 96.3,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Peintures Murales'),
    },
    {
      name: 'Peinture à l’eau Vrailatex 25',
      slug: 'peinture-a-l-eau-vrailatex-25',
      description: 'Peinture à l’eau Vrailatex 25 - Produit Rainbow Colors au prix HT indiqué.',
      price: 64.211,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Peintures Murales'),
    },
    {
      name: 'Peinture à l’eau Vrailatex 20',
      slug: 'peinture-a-l-eau-vrailatex-20',
      description: 'Peinture à l’eau Vrailatex 20 - Produit Rainbow Colors au prix HT indiqué.',
      price: 52.43,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Peintures Murales'),
    },
    {
      name: 'Peinture à l’eau Vrailatex 5',
      slug: 'peinture-a-l-eau-vrailatex-5',
      description: 'Peinture à l’eau Vrailatex 5 - Produit Rainbow Colors au prix HT indiqué.',
      price: 13.355,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Peintures Murales'),
    },
    {
      name: 'Peinture à l\'eau Super 40',
      slug: 'peinture-a-l-eau-super-40',
      description: 'Peinture à l\'eau Super 40 - Produit Rainbow Colors au prix HT indiqué.',
      price: 65.163,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Peintures Murales'),
    },
    {
      name: 'Peinture à l’eau Super 25',
      slug: 'peinture-a-l-eau-super-25',
      description: 'Peinture à l’eau Super 25 - Produit Rainbow Colors au prix HT indiqué.',
      price: 43.105,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Peintures Murales'),
    },
    {
      name: 'Peinture à l’eau Super 20',
      slug: 'peinture-a-l-eau-super-20',
      description: 'Peinture à l’eau Super 20 - Produit Rainbow Colors au prix HT indiqué.',
      price: 35.545,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Peintures Murales'),
    },
    {
      name: 'Peinture à l\'eau extra 40',
      slug: 'peinture-a-l-eau-extra-40',
      description: 'Peinture à l\'eau extra 40 - Produit Rainbow Colors au prix HT indiqué.',
      price: 51.793,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Peintures Murales'),
    },
    {
      name: 'Peinture à l\'eau extra 20',
      slug: 'peinture-a-l-eau-extra-20',
      description: 'Peinture à l\'eau extra 20 - Produit Rainbow Colors au prix HT indiqué.',
      price: 28.537,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Peintures Murales'),
    },
    {
      name: 'Peinture à l\'eau extra 5',
      slug: 'peinture-a-l-eau-extra-5',
      description: 'Peinture à l\'eau extra 5 - Produit Rainbow Colors au prix HT indiqué.',
      price: 9.55,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Peintures Murales'),
    },
    {
      name: 'Peinture à l\'eau extra 1',
      slug: 'peinture-a-l-eau-extra-1',
      description: 'Peinture à l\'eau extra 1 - Produit Rainbow Colors au prix HT indiqué.',
      price: 3.483,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Peintures Murales'),
    },
    {
      name: 'Peinture à l’eau basique 40',
      slug: 'peinture-a-l-eau-basique-40',
      description: 'Peinture à l’eau basique 40 - Produit Rainbow Colors au prix HT indiqué.',
      price: 40.446,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Peintures Murales'),
    },
    {
      name: 'Peinture à l’eau basique 35',
      slug: 'peinture-a-l-eau-basique-35',
      description: 'Peinture à l’eau basique 35 - Produit Rainbow Colors au prix HT indiqué.',
      price: 36.514,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Peintures Murales'),
    },
    {
      name: 'Peinture à l\'eau basique 20',
      slug: 'peinture-a-l-eau-basique-20',
      description: 'Peinture à l\'eau basique 20 - Produit Rainbow Colors au prix HT indiqué.',
      price: 25.279,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Peintures Murales'),
    },
    {
      name: 'Peinture à l\'eau basique 10',
      slug: 'peinture-a-l-eau-basique-10',
      description: 'Peinture à l\'eau basique 10 - Produit Rainbow Colors au prix HT indiqué.',
      price: 13.707,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Peintures Murales'),
    },
    {
      name: 'Peinture à l\'eau basique 5',
      slug: 'peinture-a-l-eau-basique-5',
      description: 'Peinture à l\'eau basique 5 - Produit Rainbow Colors au prix HT indiqué.',
      price: 8.089,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Peintures Murales'),
    },
    {
      name: 'Peinture à l\'eau rouge oxyde1',
      slug: 'peinture-a-l-eau-rouge-oxyde1',
      description: 'Peinture à l\'eau rouge oxyde1 - Produit Rainbow Colors au prix HT indiqué.',
      price: 3.563,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Traitements Métal'),
    },
    {
      name: 'Peinture à l\'eau rouge oxyde5',
      slug: 'peinture-a-l-eau-rouge-oxyde5',
      description: 'Peinture à l\'eau rouge oxyde5 - Produit Rainbow Colors au prix HT indiqué.',
      price: 13.996,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Traitements Métal'),
    },
    {
      name: 'RAINBOW PRET 25KG',
      slug: 'rainbow-pret-25kg',
      description: 'RAINBOW PRET 25KG - Produit Rainbow Colors au prix HT indiqué.',
      price: 27,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Enduits'),
    },
    {
      name: 'Enduit 40',
      slug: 'enduit-40',
      description: 'Enduit 40 - Produit Rainbow Colors au prix HT indiqué.',
      price: 51.093,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Enduits'),
    },
    {
      name: 'Enduit 20',
      slug: 'enduit-20',
      description: 'Enduit 20 - Produit Rainbow Colors au prix HT indiqué.',
      price: 26.964,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Enduits'),
    },
    {
      name: 'Enduit 5',
      slug: 'enduit-5',
      description: 'Enduit 5 - Produit Rainbow Colors au prix HT indiqué.',
      price: 9.83,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Enduits'),
    },
    {
      name: 'Enduit 800',
      slug: 'enduit-800',
      description: 'Enduit 800 - Produit Rainbow Colors au prix HT indiqué.',
      price: 3.09,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Enduits'),
    },
    {
      name: 'Laqué brillant Rainbow 0,100',
      slug: 'laque-brillant-rainbow-0-100',
      description: 'Laqué brillant Rainbow 0,100 - Produit Rainbow Colors au prix HT indiqué.',
      price: 1.909,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Peintures Bois'),
    },
    {
      name: 'Laqué brillant Rainbow 0,5',
      slug: 'laque-brillant-rainbow-0-5',
      description: 'Laqué brillant Rainbow 0,5 - Produit Rainbow Colors au prix HT indiqué.',
      price: 5.398,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Peintures Bois'),
    },
    {
      name: 'Laqué brillant Rainbow super 1',
      slug: 'laque-brillant-rainbow-super-1',
      description: 'Laqué brillant Rainbow super 1 - Produit Rainbow Colors au prix HT indiqué.',
      price: 9.673,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Peintures Bois'),
    },
    {
      name: 'Laqué brillant Rainbow 4',
      slug: 'laque-brillant-rainbow-4',
      description: 'Laqué brillant Rainbow 4 - Produit Rainbow Colors au prix HT indiqué.',
      price: 37.14,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Peintures Bois'),
    },
    {
      name: 'Laqué brillant Rainbow 18',
      slug: 'laque-brillant-rainbow-18',
      description: 'Laqué brillant Rainbow 18 - Produit Rainbow Colors au prix HT indiqué.',
      price: 160.414,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Peintures Bois'),
    },
    {
      name: 'Laqué mat Rainbow 0,5',
      slug: 'laque-mat-rainbow-0-5',
      description: 'Laqué mat Rainbow 0,5 - Produit Rainbow Colors au prix HT indiqué.',
      price: 4.762,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Peintures Bois'),
    },
    {
      name: 'Laqué mat Rainbow 1',
      slug: 'laque-mat-rainbow-1',
      description: 'Laqué mat Rainbow 1 - Produit Rainbow Colors au prix HT indiqué.',
      price: 8.4,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Peintures Bois'),
    },
    {
      name: 'Laqué mat Rainbow 4',
      slug: 'laque-mat-rainbow-4',
      description: 'Laqué mat Rainbow 4 - Produit Rainbow Colors au prix HT indiqué.',
      price: 32.052,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Peintures Bois'),
    },
    {
      name: 'Laquémat Rainbow 18',
      slug: 'laquemat-rainbow-18',
      description: 'Laquémat Rainbow 18 - Produit Rainbow Colors au prix HT indiqué.',
      price: 137.495,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Peintures Bois'),
    },
    {
      name: 'Peinture à huile Rainbow 500',
      slug: 'peinture-a-huile-rainbow-500',
      description: 'Peinture à huile Rainbow 500 - Produit Rainbow Colors au prix HT indiqué.',
      price: 3.818,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Peintures Bois'),
    },
    {
      name: 'Peinture à huile Rainbow 1',
      slug: 'peinture-a-huile-rainbow-1',
      description: 'Peinture à huile Rainbow 1 - Produit Rainbow Colors au prix HT indiqué.',
      price: 5.505,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Peintures Bois'),
    },
    {
      name: 'Peinture à huile Rainbow 4',
      slug: 'peinture-a-huile-rainbow-4',
      description: 'Peinture à huile Rainbow 4 - Produit Rainbow Colors au prix HT indiqué.',
      price: 22.605,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Peintures Bois'),
    },
    {
      name: 'Anti Rouille fer Rainbow 500',
      slug: 'anti-rouille-fer-rainbow-500',
      description: 'Anti Rouille fer Rainbow 500 - Produit Rainbow Colors au prix HT indiqué.',
      price: 3.818,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Traitements Métal'),
    },
    {
      name: 'Anti Rouille fer Rainbow 1',
      slug: 'anti-rouille-fer-rainbow-1',
      description: 'Anti Rouille fer Rainbow 1 - Produit Rainbow Colors au prix HT indiqué.',
      price: 5.725,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Traitements Métal'),
    },
    {
      name: 'Anti Rouille fer Rainbow 4',
      slug: 'anti-rouille-fer-rainbow-4',
      description: 'Anti Rouille fer Rainbow 4 - Produit Rainbow Colors au prix HT indiqué.',
      price: 22.605,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Traitements Métal'),
    },
    {
      name: 'RainbowCol 1',
      slug: 'rainbowcol-1',
      description: 'RainbowCol 1 - Produit Rainbow Colors au prix HT indiqué.',
      price: 6.85,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Peintures Murales'),
    },
    {
      name: 'RainbowCol 5',
      slug: 'rainbowcol-5',
      description: 'RainbowCol 5 - Produit Rainbow Colors au prix HT indiqué.',
      price: 29.896,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Peintures Murales'),
    },
    {
      name: 'RainbowEtanche 1',
      slug: 'rainbowetanche-1',
      description: 'RainbowEtanche 1 - Produit Rainbow Colors au prix HT indiqué.',
      price: 7.315,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Étanchéité'),
    },
    {
      name: 'RainbowEtanche 5',
      slug: 'rainbowetanche-5',
      description: 'RainbowEtanche 5 - Produit Rainbow Colors au prix HT indiqué.',
      price: 33.267,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Étanchéité'),
    },
    {
      name: 'RainbowEtanche 16',
      slug: 'rainbowetanche-16',
      description: 'RainbowEtanche 16 - Produit Rainbow Colors au prix HT indiqué.',
      price: 88.476,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Étanchéité'),
    },
    {
      name: 'RainbowEtanche 20',
      slug: 'rainbowetanche-20',
      description: 'RainbowEtanche 20 - Produit Rainbow Colors au prix HT indiqué.',
      price: 105.227,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Étanchéité'),
    },
    {
      name: 'Rainbow ECO -Etanche 25',
      slug: 'rainbow-eco-etanche-25',
      description: 'Rainbow ECO -Etanche 25 - Produit Rainbow Colors au prix HT indiqué.',
      price: 114.035,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Étanchéité'),
    },
    {
      name: 'Rainbow ECO -Etanche 5',
      slug: 'rainbow-eco-etanche-5',
      description: 'Rainbow ECO -Etanche 5 - Produit Rainbow Colors au prix HT indiqué.',
      price: 33.068,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Étanchéité'),
    },
    {
      name: 'Rainbow Etanche Finition 5',
      slug: 'rainbow-etanche-finition-5',
      description: 'Rainbow Etanche Finition 5 - Produit Rainbow Colors au prix HT indiqué.',
      price: 34.358,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Étanchéité'),
    },
    {
      name: 'Rainbow Etanche Finition 16',
      slug: 'rainbow-etanche-finition-16',
      description: 'Rainbow Etanche Finition 16 - Produit Rainbow Colors au prix HT indiqué.',
      price: 92.823,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Étanchéité'),
    },
    {
      name: 'Rainbow Etanche Finition 20',
      slug: 'rainbow-etanche-finition-20',
      description: 'Rainbow Etanche Finition 20 - Produit Rainbow Colors au prix HT indiqué.',
      price: 110.916,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Étanchéité'),
    },
    {
      name: 'Carojoint3(blanc, marron, gris c, gris f, beige c, beige f)',
      slug: 'carojoint3-blanc-marron-gris-c-gris-f-beige-c-beige-f',
      description: 'Carojoint3(blanc, marron, gris c, gris f, beige c, beige f) - Produit Rainbow Colors au prix HT indiqué.',
      price: 6.174,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Colles'),
    },
    {
      name: 'Carojoint5(blanc, marron, gris c, gris f, beige c, beige f)',
      slug: 'carojoint5-blanc-marron-gris-c-gris-f-beige-c-beige-f',
      description: 'Carojoint5(blanc, marron, gris c, gris f, beige c, beige f) - Produit Rainbow Colors au prix HT indiqué.',
      price: 9.544,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Colles'),
    },
    {
      name: 'Valsatin 1 kg',
      slug: 'valsatin-1-kg',
      description: 'Valsatin 1 kg - Produit Rainbow Colors au prix HT indiqué.',
      price: 28.088,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Peintures Murales'),
    },
    {
      name: 'Sabulador 1',
      slug: 'sabulador-1',
      description: 'Sabulador 1 - Produit Rainbow Colors au prix HT indiqué.',
      price: 28.986,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Peintures Murales'),
    },
    {
      name: 'Sticco 7',
      slug: 'sticco-7',
      description: 'Sticco 7 - Produit Rainbow Colors au prix HT indiqué.',
      price: 40.697,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Peintures Murales'),
    },
    {
      name: 'Sticco blanc 1',
      slug: 'sticco-blanc-1',
      description: 'Sticco blanc 1 - Produit Rainbow Colors au prix HT indiqué.',
      price: 7.865,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Peintures Murales'),
    },
    {
      name: 'Sticco 1000',
      slug: 'sticco-1000',
      description: 'Sticco 1000 - Produit Rainbow Colors au prix HT indiqué.',
      price: 33.48,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Peintures Murales'),
    },
    {
      name: 'Sintex 1',
      slug: 'sintex-1',
      description: 'Sintex 1 - Produit Rainbow Colors au prix HT indiqué.',
      price: 4.494,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Peintures Murales'),
    },
    {
      name: 'Tube Teintes',
      slug: 'tube-teintes',
      description: 'Tube Teintes - Produit Rainbow Colors au prix HT indiqué.',
      price: 2.191,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Peintures Murales'),
    },
    {
      name: 'Rexim 1',
      slug: 'rexim-1',
      description: 'Rexim 1 - Produit Rainbow Colors au prix HT indiqué.',
      price: 4.494,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Enduits de Finition'),
    },
    {
      name: 'Rexim 4',
      slug: 'rexim-4',
      description: 'Rexim 4 - Produit Rainbow Colors au prix HT indiqué.',
      price: 20.448,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Enduits de Finition'),
    },
    {
      name: 'Rexim 16',
      slug: 'rexim-16',
      description: 'Rexim 16 - Produit Rainbow Colors au prix HT indiqué.',
      price: 79.884,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Enduits de Finition'),
    },
    {
      name: 'Primer balnc 4',
      slug: 'primer-balnc-4',
      description: 'Primer balnc 4 - Produit Rainbow Colors au prix HT indiqué.',
      price: 24.681,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Traitements Métal'),
    },
    {
      name: 'Primer balnc 16',
      slug: 'primer-balnc-16',
      description: 'Primer balnc 16 - Produit Rainbow Colors au prix HT indiqué.',
      price: 97.845,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Traitements Métal'),
    },
    {
      name: 'Primer balnc 18',
      slug: 'primer-balnc-18',
      description: 'Primer balnc 18 - Produit Rainbow Colors au prix HT indiqué.',
      price: 109.517,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Traitements Métal'),
    },
    {
      name: 'DILUANT 0,125',
      slug: 'diluant-0-125',
      description: 'DILUANT 0,125 - Produit Rainbow Colors au prix HT indiqué.',
      price: 1.371,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Traitements Métal'),
    },
    {
      name: 'DILUANT 0,8',
      slug: 'diluant-0-8',
      description: 'DILUANT 0,8 - Produit Rainbow Colors au prix HT indiqué.',
      price: 5.088,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Traitements Métal'),
    },
    {
      name: 'DILUANT 4',
      slug: 'diluant-4',
      description: 'DILUANT 4 - Produit Rainbow Colors au prix HT indiqué.',
      price: 25.145,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Traitements Métal'),
    },
    {
      name: 'ESSENCE 0,125',
      slug: 'essence-0-125',
      description: 'ESSENCE 0,125 - Produit Rainbow Colors au prix HT indiqué.',
      price: 1.119,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Traitements Métal'),
    },
    {
      name: 'ESSENCE 0,8',
      slug: 'essence-0-8',
      description: 'ESSENCE 0,8 - Produit Rainbow Colors au prix HT indiqué.',
      price: 3.626,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Traitements Métal'),
    },
    {
      name: 'ESSENCE 4',
      slug: 'essence-4',
      description: 'ESSENCE 4 - Produit Rainbow Colors au prix HT indiqué.',
      price: 17.488,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Traitements Métal'),
    },
    {
      name: 'MAGMA INTENSO 40KG',
      slug: 'magma-intenso-40kg',
      description: 'MAGMA INTENSO 40KG - Produit Rainbow Colors au prix HT indiqué.',
      price: 58.243,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Peintures Murales'),
    },
    {
      name: 'MAGMA ULTRA SHILED 40KG',
      slug: 'magma-ultra-shiled-40kg',
      description: 'MAGMA ULTRA SHILED 40KG - Produit Rainbow Colors au prix HT indiqué.',
      price: 70.128,
      oldPrice: null,
      stock: 100,
      stockStatus: 'IN_STOCK',
      badge: null,
      image: 'images/logo ranbow colors.jpeg',
      features: JSON.stringify([]),
      categoryId: getCatId('Peintures Murales'),
    },
  ];

  // Keep old products in the database for existing orders, but hide them
  // from the public catalog because this new list replaces the old catalog.
  const newProductSlugs = productsData.map((p) => p.slug);
  await prisma.product.updateMany({
    where: {
      slug: { notIn: newProductSlugs },
    },
    data: {
      isActive: false,
    },
  });

  for (const p of productsData) {
    await prisma.product.upsert({
      where: { slug: p.slug },
      update: {
        name: p.name,
        description: p.description,
        price: p.price,
        oldPrice: p.oldPrice,
        stock: p.stock,
        stockStatus: p.stockStatus,
        badge: p.badge,
        image: p.image,
        images: JSON.stringify([p.image]),
        features: p.features,
        categoryId: p.categoryId,
        isActive: true,
      },
      create: {
        ...p,
        images: JSON.stringify([p.image]),
        isActive: true,
      },
    });
  }

  console.log('✅ Seed completed successfully!');
  console.log('👤 Admin: admin@rainbow-colors.tn / admin123');
  console.log('👤 Customer: client@demo.tn / client123');
  console.log(`📦 ${productsData.length} products seeded`);
  console.log(`📁 ${categoriesData.length} categories seeded`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
